---
  apiVersion: v2
  description: A common powered chart template. This can be useful for small projects that don't have their own chart.
  name: app-template
  version: 4.4.1
  kubeVersion: ">=1.28.0-0"
  dependencies:
    - name: common
      repository: https://myalbum.github.io/helm-charts
      version: 4.4.1
  sources:
    - https://github.com/MyAlbum/helm-charts
  annotations:
    artifacthub.io/changes: |-
      - kind: changed
        description: |-
          Upgraded the common library to v4.4.1
        links:
          - name: Upgrade notes
            url: https://myalbum.github.io/helm-charts/docs/app-template/upgrade-instructions/
          - name: Detailed release notes
            url: https://github.com/myalbum/helm-charts/releases/tag/common-4.4.1
